import sqlite3
import json
import os

DB_FILE = 'saradakosh.db'
OUTPUT_FILE = 'webapp/js/schedule_data.js'

def generate():
    if not os.path.exists(DB_FILE):
        print(f"{DB_FILE} not found. Ensure setup_schedule_db.py has been run.")
        return

    conn = sqlite3.connect(DB_FILE)
    cursor = conn.cursor()

    # Fetch settings
    cursor.execute('SELECT start_date, google_meet_link FROM schedule_settings LIMIT 1')
    settings = cursor.fetchone()
    if not settings:
        start_date = ""
        meet_link = ""
    else:
        start_date, meet_link = settings

    # Fetch topics
    cursor.execute('SELECT name, playlist_link FROM schedule_topics ORDER BY order_idx ASC')
    topics = [{'name': row[0], 'link': row[1]} for row in cursor.fetchall()]

    conn.close()

    # Build the config dictionary
    config = {
        'startDate': start_date,
        'googleMeetLink': meet_link,
        'topics': topics
    }

    # Write to schedule_data.js
    js_content = f"// AUTO-GENERATED BY generate_schedule_data.py\nconst scheduleConfig = {json.dumps(config, indent=4)};\n"
    
    with open(OUTPUT_FILE, 'w', encoding='utf-8') as f:
        f.write(js_content)
        
    print(f"Generated {OUTPUT_FILE} successfully.")

if __name__ == '__main__':
    generate()
